apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapphp
  labels:
    app: webapphp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapphp
  template:
    metadata:
      labels:
        app: webapphp
    spec:
      containers:
      - name: nginx-server
        image: nginx:latest
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test-volume
        ports:
        - containerPort: 80
      - name: ubuntu-server
        image: ubuntu
        volumeMounts:
        - mountPath: /pod-data
          name: test-volume
        command: ["/bin/sh"]
        args:      
            - "-c"       
            - >
              while true; do          
              date >> /pod-data/index.html;          
              echo Hello from the second container 
              >> /pod-data/index.html;          sleep 1;       done 
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: I:\k8s\storage\data
          # this field is optional https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: webapphp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006