apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhpv
  labels:
    app: webhpv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhpv
  template:
    metadata:
      labels:
        app: webhpv
    spec:
      containers:
      - name: nginxhpv
        image: nginx:latest
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: volumehpv
        ports:
        - containerPort: 80
      - name: ubuntuhpv
        image: ubuntu
        volumeMounts:
        - mountPath: /pod-data
          name: volumehpv
        command: ["/bin/sh"]
        args:      
            - "-c"       
            - >
              while true; do          
              date >> /pod-data/index.html;          
              echo "Hello Confluxsys - from the second container<br>"
              >> /pod-data/index.html;          sleep 1;       done 
      volumes:
      - name: volumehpv
        hostPath:
          # directory location on host or try /run/desktop/mnt/host/i
          path: /run/desktop/mnt/host/i/k8s/storage/data
          # this field is optional https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: webservice-hpv
spec:
  type: NodePort
  selector:
    app: webhpv
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005