apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnpv
  labels:
    app: webnpv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnpv
  template:
    metadata:
      labels:
        app: webnpv
    spec:
      containers:
      - name: nginxnpv
        image: nginx:latest
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: volumenpv
        ports:
        - containerPort: 80
      - name: ubuntunpv
        image: ubuntu
        volumeMounts:
        - mountPath: /pod-data
          name: volumenpv
        command: ["/bin/sh"]
        args:      
            - "-c"       
            - >
              while true; do          
              date >> /pod-data/index.html;          
              echo "Hello from the second container<br>"
              >> /pod-data/index.html;          sleep 1;       done 
      volumes:
      - name: volumenpv
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webservice-npv
spec:
  type: NodePort
  selector:
    app: webnpv
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009